### ISSUE TITLE
compatibility with kdbush 4.x

### ISSUE THREAD

**Issue by quarl** [mourner/geokdbush#16]
kdbush 4.x changed the internal interface so that index.points no longer exists, but the latest version of geokdbush still relies on it.

I was able to work around it by manually setting index.points to an array matching what I wanted (lng/lat points).

It might make sense to just return an index.

**Comment by tkafka** [comment]
I made a fork that uses 4.x - the api changed though, as kdbush 4.x only returns indices, and it it up to user to store the data.

https://www.npmjs.com/package/geokdbush-tk

**Comment by tkafka** [comment]
I forked the geokdbush and updated it to work with kdbush 4.x (and also to use ES6 and modules): https://www.npmjs.com/package/geokdbush-tk

Cc @mourner

**Comment by uniquenode** [comment]
@tkafka does your lib require ESM? I am getting the following error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/xxx/node_modules/geokdbush-tk/index.js from /home/xxx/file.ts not supported
```

**Comment by zakjan** [comment]
@tkafka Thanks for the fork, works well. Would you be able to create a PR with the necessary changes to propagate it back here?

**Comment by mourner** [comment]
Apologies for the delay. I'm now releasing geokdbush v2 that works with KDBush v4, and updated the readme example on how to use it.

**Comment by tkafka** [comment]
@mourner Thank you for the update! I added a notice about geokdbush now being updated to [my fork](https://www.npmjs.com/package/geokdbush-tk) and deprecated it :).

**Comment by zakjan** [comment]
@mourner Thanks! 🙌

**Comment by mourner** [comment]
@tkafka thank you for maintaining a fork until I got to this!
