### ISSUE TITLE
CommonJS and kdbush

### ISSUE THREAD

**Issue by dnohr** [mourner/geokdbush#17]
Hi @mourner,

First of all, thank you so much for your work on this project. I've tried several libraries, and this is by far the fastest nearby geo library I've used in a few non-commercial projects.

Unfortunately, it's not working anymore due to the [lack of CommonJS](https://github.com/mourner/kdbush/issues/39) support in kdbush. I've integrated geokdbush into my web application, which I cannot easily migrate to ESM. It would be different if it was a simple standalone script running on the backend.

If possible, would it be feasible to reintroduce CommonJS support to kdbush and update this library to reflect v4.* of kdbush? That would be greatly appreciated.

Thanks!

**Comment by mourner** [comment]
Apologies for a late response. Unfortunately I no longer intend to support CommonJS in my libraries. I released a new version of Geokdbush (v2) that supports KDBush v4, but it's ESM-only too. Please use older versions if you need legacy compatibility.
