### ISSUE TITLE
Added Typescript definition to DefinitelyTyped

### ISSUE THREAD

**Issue by DenisCarriere** [mourner/geokdbush#4]
Just a heads up, I've submitted a PR to add the Typescript definition to `geokdbush`.

Once it's merged and published, we can add `@types/geokdbush` to this README.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17367

**Comment by mourner** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7638212-302540329_1-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by DenisCarriere** [comment]
👍
